---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rails-apps.jgaskins.dev
spec:
  group: jgaskins.dev
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                image_pull_policy:
                  type: string
                  default: "IfNotPresent"
                image_pull_secrets:
                  type: array
                  default: []
                  items:
                    type: string
                envFrom: &envFrom
                  type: array
                  default: []
                  items:
                    type: object
                    properties:
                      secretRef:
                        type: object
                        nullable: true
                        properties:
                          name:
                            type: string
                        required:
                          - name
                      configMapRef:
                        type: object
                        nullable: true
                        properties:
                          name:
                            type: string
                        required:
                          - name
                env: &env
                  type: array
                  default: []
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                        nullable: true
                      valueFrom:
                        type: object
                        nullable: true
                        properties:
                          configMapKeyRef:
                            type: object
                            nullable: true
                            properties:
                              name:
                                type: string
                              key:
                                type: string
                          secretKeyRef:
                            type: object
                            nullable: true
                            properties:
                              name:
                                type: string
                              key:
                                type: string
                          fieldRef:
                            type: object
                            nullable: true
                            properties:
                              fieldPath:
                                type: string
                directories:
                  type: array
                  default: []
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      path:
                        type: string
                      files:
                        type: array
                        nullable: true
                        items:
                          type: object
                          properties:
                            filename:
                              type: string
                            content:
                              type: string
                        required:
                          - filename
                          - content
                      persistent_storage:
                        type: object
                        nullable: true
                        properties:
                          access_modes:
                            type: array
                            items:
                              type: string
                          storage_class:
                            type: string
                            nullable: true
                          size:
                            type: string
                        required:
                          - access_modes
                          - size
                    required:
                      - name
                      - path
                entrypoints:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      command:
                        type: array
                        nullable: true
                        items:
                          type: string
                      domain:
                        type: string
                        nullable: true
                      port:
                        type: integer
                        nullable: true
                      path:
                        type: string
                        default: "/"
                      path_type:
                        type: string
                        default: "Prefix"
                      replicas:
                        type: integer
                        default: 1
                      resources:
                        type: object
                        nullable: true
                        properties:
                          requests: &resources
                            type: object
                            nullable: true
                            properties:
                              cpu: { type: string }
                              memory: { type: string }
                          limits: *resources
                      health_check:
                        type: object
                        nullable: true
                        properties:
                          path:
                            type: string
                            default: "/"
                          start_after:
                            type: integer
                            nullable: true
                          run_every:
                            type: integer
                            nullable: true
                          failure_threshold:
                            type: integer
                            nullable: true
                      ingress:
                        type: object
                        nullable: true
                        properties:
                          annotations:
                            type: object
                            nullable: true
                            x-kubernetes-preserve-unknown-fields: true
                      envFrom: *envFrom
                      env: *env
                      service_account:
                        type: string
                        nullable: true
                    required:
                      - name
                before_update:
                  type: object
                  properties:
                    command:
                      type: array
                      items:
                        type: string
                    env: *env
                    envFrom: *envFrom
                before_create:
                  type: object
                  properties:
                    command:
                      type: array
                      items:
                        type: string
                    env: *env
                    envFrom: *envFrom
                service_account:
                  type: string
                  nullable: true

              required:
                - image
                - env
                - entrypoints
  scope: Namespaced
  names:
    plural: rails-apps
    singular: rails-app
    kind: RailsApp
    shortNames: []
