---
apiVersion: jgaskins.dev/v1beta1
kind: RailsApp
metadata:
  name: busybox
  namespace: default
spec:
  image: busybox
  image_pull_policy: Always
  entrypoints:
    - name: task
      command: [sh, "-c", "sleep 300"]

  before_create:
    command: [echo, "Creating..."]

  before_update:
    command: [echo, "Updating..."]
